SHELL=/bin/bash
summary/all.tex: gen
	echo '\summaryDGHyper{\texttt{dg\_0}}{out/049_dg_0_11100}{\texttt{out/049\_dg\_0\_11100}}' >> summary/all.tex
	echo '\summarySection{Rule(s)}' >> summary/all.tex
	echo '\summaryRule{BA 92-91 §R1}{\summaryRuleSpan{out/051_r_0_11300110}{out/051\_r\_0\_11300110}}{}{}{out/052_r_0_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{BA 92-77 §R1}{\summaryRuleSpan{out/054_r_4_11300110}{out/054\_r\_4\_11300110}}{}{}{out/055_r_4_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Diels Adler 1 ionization}{\summaryRuleSpan{out/057_r_169_11300110}{out/057\_r\_169\_11300110}}{}{}{out/058_r_169_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{McL ionization §Y1}{\summaryRuleSpan{out/060_r_172_11300110}{out/060\_r\_172\_11300110}}{}{}{out/061_r_172_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{deprotonation radical §Y2}{\summaryRuleSpan{out/063_r_6_11300110}{out/063\_r\_6\_11300110}}{}{}{out/064_r_6_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{deprotonation proton §Y2}{\summaryRuleSpan{out/066_r_7_11300110}{out/066\_r\_7\_11300110}}{}{}{out/067_r_7_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{BA 91-91 full ring}{\summaryRuleSpan{out/069_r_1_11300110}{out/069\_r\_1\_11300110}}{}{}{out/070_r_1_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{BA 91-65}{\summaryRuleSpan{out/072_r_2_11300110}{out/072\_r\_2\_11300110}}{}{}{out/073_r_2_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{BA 65-39}{\summaryRuleSpan{out/075_r_3_11300110}{out/075\_r\_3\_11300110}}{}{}{out/076_r_3_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{BA 77-51}{\summaryRuleSpan{out/078_r_5_11300110}{out/078\_r\_5\_11300110}}{}{}{out/079_r_5_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{dissoziation of a sigma bond for Elements with low IE §R1}{\summaryRuleSpan{out/081_r_9_11300110}{out/081\_r\_9\_11300110}}{}{}{out/082_r_9_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site unsaturated §Y6}{\summaryRuleSpan{out/084_r_10_11300110}{out/084\_r\_10\_11300110}}{}{}{out/085_r_10_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site unsaturated §Y5}{\summaryRuleSpan{out/087_r_11_11300110}{out/087\_r\_11\_11300110}}{}{}{out/088_r_11_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site unsaturated §Y5}{\summaryRuleSpan{out/090_r_12_11300110}{out/090\_r\_12\_11300110}}{}{}{out/091_r_12_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site unsaturated §Y5}{\summaryRuleSpan{out/093_r_13_11300110}{out/093\_r\_13\_11300110}}{}{}{out/094_r_13_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated §S3-4Y5}{\summaryRuleSpan{out/096_r_14_11300110}{out/096\_r\_14\_11300110}}{}{}{out/097_r_14_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated §S2-3Y4}{\summaryRuleSpan{out/099_r_15_11300110}{out/099\_r\_15\_11300110}}{}{}{out/100_r_15_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated §S2-3Y4}{\summaryRuleSpan{out/102_r_16_11300110}{out/102\_r\_16\_11300110}}{}{}{out/103_r_16_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated inductive §S2-3Y4}{\summaryRuleSpan{out/105_r_17_11300110}{out/105\_r\_17\_11300110}}{}{}{out/106_r_17_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated rH §Y4S3-5}{\summaryRuleSpan{out/108_r_18_11300110}{out/108\_r\_18\_11300110}}{}{}{out/109_r_18_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated alpha §Y1S3-5}{\summaryRuleSpan{out/111_r_19_11300110}{out/111\_r\_19\_11300110}}{}{}{out/112_r_19_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated rH §S3-4Y5R8}{\summaryRuleSpan{out/114_r_20_11300110}{out/114\_r\_20\_11300110}}{}{}{out/115_r_20_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated alpha §S2-3Y4R8}{\summaryRuleSpan{out/117_r_21_11300110}{out/117\_r\_21\_11300110}}{}{}{out/118_r_21_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated rH §Y6S3-4}{\summaryRuleSpan{out/120_r_22_11300110}{out/120\_r\_22\_11300110}}{}{}{out/121_r_22_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated alpha}{\summaryRuleSpan{out/123_r_23_11300110}{out/123\_r\_23\_11300110}}{}{}{out/124_r_23_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated inductive §Y2S1-3Y5}{\summaryRuleSpan{out/126_r_25_11300110}{out/126\_r\_25\_11300110}}{}{}{out/127_r_25_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated inductive §Y2S1-3Y5}{\summaryRuleSpan{out/129_r_26_11300110}{out/129\_r\_26\_11300110}}{}{}{out/130_r_26_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H transition receptor site saturated inductive §Y2S1-3Y5}{\summaryRuleSpan{out/132_r_27_11300110}{out/132\_r\_27\_11300110}}{}{}{out/133_r_27_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{2 H transition rH1 §Y5Y8}{\summaryRuleSpan{out/135_r_28_11300110}{out/135\_r\_28\_11300110}}{}{}{out/136_r_28_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{2 H transition charge §Y5Y8}{\summaryRuleSpan{out/138_r_29_11300110}{out/138\_r\_29\_11300110}}{}{}{out/139_r_29_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{2 H transition rH2 split §Y5Y8}{\summaryRuleSpan{out/141_r_30_11300110}{out/141\_r\_30\_11300110}}{}{}{out/142_r_30_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Substituion §R1S2-3Y4}{\summaryRuleSpan{out/144_r_31_11300110}{out/144\_r\_31\_11300110}}{}{}{out/145_r_31_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Elimination §R1S2-3R4Y5}{\summaryRuleSpan{out/147_r_32_11300110}{out/147\_r\_32\_11300110}}{}{}{out/148_r_32_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{one bond cleavage 4.3 var1}{\summaryRuleSpan{out/150_r_33_11300110}{out/150\_r\_33\_11300110}}{}{}{out/151_r_33_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{one bond cleavage 4.3 var2}{\summaryRuleSpan{out/153_r_34_11300110}{out/153\_r\_34\_11300110}}{}{}{out/154_r_34_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{dissoziation of a sigma bond for alkans 4.7 §R1R3R4R5}{\summaryRuleSpan{out/156_r_45_11300110}{out/156\_r\_45\_11300110}}{}{}{out/157_r_45_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{dissoziation of a sigma bond for alkans 4.8}{\summaryRuleSpan{out/159_r_46_11300110}{out/159\_r\_46\_11300110}}{}{}{out/160_r_46_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a saturated site 4.9 §R1R3R4Y5}{\summaryRuleSpan{out/162_r_47_11300110}{out/162\_r\_47\_11300110}}{}{}{out/163_r_47_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a saturated site 4.9 §R1R3R4Y5}{\summaryRuleSpan{out/164_r_47_11300110}{out/164\_r\_47\_11300110}}{}{}{out/165_r_47_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a saturated site 4.10 §Y1}{\summaryRuleSpan{out/167_r_48_11300110}{out/167\_r\_48\_11300110}}{}{}{out/168_r_48_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a unsaturated heteroatom 4.11 §R1R3Y4}{\summaryRuleSpan{out/170_r_49_11300110}{out/170\_r\_49\_11300110}}{}{}{out/171_r_49_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a alkene charge left 4.12\_1 §R1}{\summaryRuleSpan{out/173_r_50_11300110}{out/173\_r\_50\_11300110}}{}{}{out/174_r_50_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a alkene charge right 4.12\_2 §R1}{\summaryRuleSpan{out/176_r_51_11300110}{out/176\_r\_51\_11300110}}{}{}{out/177_r_51_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a saturated site 4.13\_1}{\summaryRuleSpan{out/179_r_52_11300110}{out/179\_r\_52\_11300110}}{}{}{out/180_r_52_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a saturated site 4.13\_2}{\summaryRuleSpan{out/182_r_53_11300110}{out/182\_r\_53\_11300110}}{}{}{out/183_r_53_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a unsaturated heteroatom 4.14}{\summaryRuleSpan{out/185_r_54_11300110}{out/185\_r\_54\_11300110}}{}{}{out/186_r_54_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a alkene 4.15 prod 1 left charge}{\summaryRuleSpan{out/188_r_55_11300110}{out/188\_r\_55\_11300110}}{}{}{out/189_r_55_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a alkene 4.15 prod 1 right charge}{\summaryRuleSpan{out/191_r_56_11300110}{out/191\_r\_56\_11300110}}{}{}{out/192_r_56_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a alkene 4.15 prod 2 left charge}{\summaryRuleSpan{out/194_r_57_11300110}{out/194\_r\_57\_11300110}}{}{}{out/195_r_57_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a alkene 4.15 prod 2 right charge}{\summaryRuleSpan{out/197_r_58_11300110}{out/197\_r\_58\_11300110}}{}{}{out/198_r_58_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a alkene 4.15 2nd prod 1}{\summaryRuleSpan{out/200_r_59_11300110}{out/200\_r\_59\_11300110}}{}{}{out/201_r_59_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a alkene 4.15 2nd prod 2}{\summaryRuleSpan{out/203_r_60_11300110}{out/203\_r\_60\_11300110}}{}{}{out/204_r_60_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a saturated site 4.17\_1}{\summaryRuleSpan{out/206_r_62_11300110}{out/206\_r\_62\_11300110}}{}{}{out/207_r_62_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a saturated site 4.17\_2}{\summaryRuleSpan{out/209_r_63_11300110}{out/209\_r\_63\_11300110}}{}{}{out/210_r_63_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{radical induced (alpha-)clevage for a saturated site 4.17\_3}{\summaryRuleSpan{out/212_r_64_11300110}{out/212\_r\_64\_11300110}}{}{}{out/213_r_64_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage odd electron 1 4.18 §R1Y2}{\summaryRuleSpan{out/215_r_65_11300110}{out/215\_r\_65\_11300110}}{}{}{out/216_r_65_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage odd electron 2 4.19 §R1R3Y4}{\summaryRuleSpan{out/218_r_66_11300110}{out/218\_r\_66\_11300110}}{}{}{out/219_r_66_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage odd electron 3 4.19 §R1R3Y2}{\summaryRuleSpan{out/221_r_67_11300110}{out/221\_r\_67\_11300110}}{}{}{out/222_r_67_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage even electron 1 4.20 §R1Y2}{\summaryRuleSpan{out/224_r_68_11300110}{out/224\_r\_68\_11300110}}{}{}{out/225_r_68_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage even electron 2 4.21 §R1Y2}{\summaryRuleSpan{out/227_r_69_11300110}{out/227\_r\_69\_11300110}}{}{}{out/228_r_69_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage odd electron 4.22}{\summaryRuleSpan{out/230_r_70_11300110}{out/230\_r\_70\_11300110}}{}{}{out/231_r_70_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage odd electron 4.23 prod 1}{\summaryRuleSpan{out/233_r_71_11300110}{out/233\_r\_71\_11300110}}{}{}{out/234_r_71_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage odd electron 4.23 prod 1}{\summaryRuleSpan{out/236_r_72_11300110}{out/236\_r\_72\_11300110}}{}{}{out/237_r_72_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage odd electron 4.24 prod 1}{\summaryRuleSpan{out/239_r_73_11300110}{out/239\_r\_73\_11300110}}{}{}{out/240_r_73_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage odd electron 4.24 prod 1}{\summaryRuleSpan{out/242_r_74_11300110}{out/242\_r\_74\_11300110}}{}{}{out/243_r_74_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage odd electron 4.25 reactant 1 §R1R3}{\summaryRuleSpan{out/245_r_75_11300110}{out/245\_r\_75\_11300110}}{}{}{out/246_r_75_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage odd electron 4.25 reactant 2 §R1R3}{\summaryRuleSpan{out/248_r_76_11300110}{out/248\_r\_76\_11300110}}{}{}{out/249_r_76_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage even electron 4.26 step 1 alpha §R1R6}{\summaryRuleSpan{out/251_r_77_11300110}{out/251\_r\_77\_11300110}}{}{}{out/252_r_77_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage even electron 4.26 step 2 inductive §R5}{\summaryRuleSpan{out/254_r_78_11300110}{out/254\_r\_78\_11300110}}{}{}{out/255_r_78_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage even electron 4.27 step 1 alpha §R1R3}{\summaryRuleSpan{out/257_r_79_11300110}{out/257\_r\_79\_11300110}}{}{}{out/258_r_79_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage even electron 4.27 step 2 inductive §R1}{\summaryRuleSpan{out/260_r_80_11300110}{out/260\_r\_80\_11300110}}{}{}{out/261_r_80_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage even electron 4.28 step 1 chemical ionization §R1}{\summaryRuleSpan{out/263_r_81_11300110}{out/263\_r\_81\_11300110}}{}{}{out/264_r_81_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage even electron 4.28 step 2 inductive §R1}{\summaryRuleSpan{out/266_r_82_11300110}{out/266\_r\_82\_11300110}}{}{}{out/267_r_82_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage even electron 4.29 §R1}{\summaryRuleSpan{out/269_r_83_11300110}{out/269\_r\_83\_11300110}}{}{}{out/270_r_83_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Ring spaltung generell 4.30}{\summaryRuleSpan{out/272_r_84_11300110}{out/272\_r\_84\_11300110}}{}{}{out/273_r_84_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{retro diels alder charge conservation 4.31 alpha 1 §R1}{\summaryRuleSpan{out/275_r_85_11300110}{out/275\_r\_85\_11300110}}{}{}{out/276_r_85_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{retro diels alder charge conservation 4.31 alpha 2 §R1}{\summaryRuleSpan{out/278_r_86_11300110}{out/278\_r\_86\_11300110}}{}{}{out/279_r_86_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{retro diels alder charge drift 4.32 alpha §R1}{\summaryRuleSpan{out/281_r_87_11300110}{out/281\_r\_87\_11300110}}{}{}{out/282_r_87_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{retro diels alder charge drift 4.32 ind §R1}{\summaryRuleSpan{out/284_r_88_11300110}{out/284\_r\_88\_11300110}}{}{}{out/285_r_88_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{gamma H-migr. to unsat. group with beta cleavage 4.33 rH §R1}{\summaryRuleSpan{out/287_r_89_11300110}{out/287\_r\_89\_11300110}}{}{}{out/288_r_89_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{gamma H-migr. to unsat. group with beta cleavage 4.33 alpha 1 §R1}{\summaryRuleSpan{out/290_r_90_11300110}{out/290\_r\_90\_11300110}}{}{}{out/291_r_90_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{gamma H-migr. to unsat. group with beta cleavage 4.33 alpha 2 §R1}{\summaryRuleSpan{out/293_r_91_11300110}{out/293\_r\_91\_11300110}}{}{}{out/294_r_91_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{gamma H-migr. to unsat. group with beta cleavage 4.34 rH §R1}{\summaryRuleSpan{out/296_r_92_11300110}{out/296\_r\_92\_11300110}}{}{}{out/297_r_92_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{gamma H-migr. to unsat. group with beta cleavage 4.34 inductive §R1}{\summaryRuleSpan{out/299_r_93_11300110}{out/299\_r\_93\_11300110}}{}{}{out/300_r_93_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{gamma H-migr. to unsaturated group Odd electron Ion 4.35 rH alpha}{\summaryRuleSpan{out/302_r_94_11300110}{out/302\_r\_94\_11300110}}{}{}{out/303_r_94_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{gamma H-migr. to unsaturated group Odd electron Ion 4.36 charge move}{\summaryRuleSpan{out/305_r_95_11300110}{out/305\_r\_95\_11300110}}{}{}{out/306_r_95_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{gamma H-migr. to unsaturated group Odd electron Ion 4.36 rH alpha}{\summaryRuleSpan{out/308_r_96_11300110}{out/308\_r\_96\_11300110}}{}{}{out/309_r_96_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H-migration to unsat. hetroatom and clevage of neighb. bond 4.37 rH}{\summaryRuleSpan{out/311_r_97_11300110}{out/311\_r\_97\_11300110}}{}{}{out/312_r_97_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H-migration to unsat. hetroatom and clevage of neighb. bond 4.37 rd}{\summaryRuleSpan{out/314_r_98_11300110}{out/314\_r\_98\_11300110}}{}{}{out/315_r_98_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H-migration to unsat. hetroatom and clevage of neighb. bond 4.38 rH}{\summaryRuleSpan{out/317_r_99_11300110}{out/317\_r\_99\_11300110}}{}{}{out/318_r_99_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H-migration to unsat. hetroatom and clevage of neighb. bond 4.38 ind}{\summaryRuleSpan{out/320_r_100_11300110}{out/320\_r\_100\_11300110}}{}{}{out/321_r_100_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H-migration to unsat. hetroatom and clevage of neighb. bond 4.38 ind}{\summaryRuleSpan{out/323_r_101_11300110}{out/323\_r\_101\_11300110}}{}{}{out/324_r_101_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H-migration to unsat. hetroatom and clevage of neighb. bond 4.39 rH}{\summaryRuleSpan{out/326_r_102_11300110}{out/326\_r\_102\_11300110}}{}{}{out/327_r_102_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H-migration to unsat. hetroatom and clevage of neighb. bond 4.39 alpha}{\summaryRuleSpan{out/329_r_103_11300110}{out/329\_r\_103\_11300110}}{}{}{out/330_r_103_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H-migration to unsat. hetroatom and clevage of neighb. bond 4.40 rH}{\summaryRuleSpan{out/332_r_104_11300110}{out/332\_r\_104\_11300110}}{}{}{out/333_r_104_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H-migration to unsat. hetroatom and clevage of neighb. bond 4.40 ind}{\summaryRuleSpan{out/335_r_105_11300110}{out/335\_r\_105\_11300110}}{}{}{out/336_r_105_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H-migr to unsat. hetrostructur and clevage of neighb. bond 4.41 rH §Y2R12}{\summaryRuleSpan{out/338_r_106_11300110}{out/338\_r\_106\_11300110}}{}{}{out/339_r_106_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H-migr to unsat. hetrostructur and clevage of neighb. bond 4.41 ind prod 1 §Y1R12}{\summaryRuleSpan{out/341_r_107_11300110}{out/341\_r\_107\_11300110}}{}{}{out/342_r_107_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H-migr to unsat. hetrostructur and clevage of neighb. bond 4.41 ind prod 2 §Y1R12}{\summaryRuleSpan{out/344_r_108_11300110}{out/344\_r\_108\_11300110}}{}{}{out/345_r_108_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{displacement reaction 4.42 rd §R1}{\summaryRuleSpan{out/347_r_109_11300110}{out/347\_r\_109\_11300110}}{}{}{out/348_r_109_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{displacement reaction 4.43}{\summaryRuleSpan{out/350_r_110_11300110}{out/350\_r\_110\_11300110}}{}{}{out/351_r_110_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{displacement reaction 4.43 rH}{\summaryRuleSpan{out/353_r_111_11300110}{out/353\_r\_111\_11300110}}{}{}{out/354_r_111_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{displacement reaction 4.44 ind}{\summaryRuleSpan{out/356_r_112_11300110}{out/356\_r\_112\_11300110}}{}{}{out/357_r_112_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{displacement reaction 4.44 rH}{\summaryRuleSpan{out/359_r_113_11300110}{out/359\_r\_113\_11300110}}{}{}{out/360_r_113_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{displacement reaction 4.45 rH §R1R7}{\summaryRuleSpan{out/362_r_114_11300110}{out/362\_r\_114\_11300110}}{}{}{out/363_r_114_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{displacement reaction 4.45 alpha §R1R6}{\summaryRuleSpan{out/365_r_115_11300110}{out/365\_r\_115\_11300110}}{}{}{out/366_r_115_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{displacement reaction 4.46 rH §R2R8}{\summaryRuleSpan{out/368_r_116_11300110}{out/368\_r\_116\_11300110}}{}{}{out/369_r_116_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{displacement reaction 4.46 rH2 var 1 §R2R7}{\summaryRuleSpan{out/371_r_117_11300110}{out/371\_r\_117\_11300110}}{}{}{out/372_r_117_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{displacement reaction 4.46 rH2 var 2 §R2R7}{\summaryRuleSpan{out/374_r_118_11300110}{out/374\_r\_118\_11300110}}{}{}{out/375_r_118_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.1 rH -0.6}{\summaryRuleSpan{out/377_r_119_11300110}{out/377\_r\_119\_11300110}}{}{}{out/378_r_119_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.1 alpha 1.0}{\summaryRuleSpan{out/380_r_120_11300110}{out/380\_r\_120\_11300110}}{}{}{out/381_r_120_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.1 rH 2.5}{\summaryRuleSpan{out/383_r_121_11300110}{out/383\_r\_121\_11300110}}{}{}{out/384_r_121_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.1 alpha 1.7}{\summaryRuleSpan{out/386_r_122_11300110}{out/386\_r\_122\_11300110}}{}{}{out/387_r_122_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.1 rH 3.0}{\summaryRuleSpan{out/389_r_123_11300110}{out/389\_r\_123\_11300110}}{}{}{out/390_r_123_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.1 rH 0.3}{\summaryRuleSpan{out/392_r_124_11300110}{out/392\_r\_124\_11300110}}{}{}{out/393_r_124_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.1 alpha 1.1}{\summaryRuleSpan{out/395_r_125_11300110}{out/395\_r\_125\_11300110}}{}{}{out/396_r_125_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.2 bidirectional down}{\summaryRuleSpan{out/398_r_126_11300110}{out/398\_r\_126\_11300110}}{}{}{out/399_r_126_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.2 bidirectional up}{\summaryRuleSpan{out/401_r_127_11300110}{out/401\_r\_127\_11300110}}{}{}{out/402_r_127_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.2 alpha 1.1}{\summaryRuleSpan{out/404_r_128_11300110}{out/404\_r\_128\_11300110}}{}{}{out/405_r_128_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.2 inductive 4.5}{\summaryRuleSpan{out/407_r_129_11300110}{out/407\_r\_129\_11300110}}{}{}{out/408_r_129_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.2 inductive 2.1}{\summaryRuleSpan{out/410_r_130_11300110}{out/410\_r\_130\_11300110}}{}{}{out/411_r_130_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.2 inductive 3.1}{\summaryRuleSpan{out/413_r_131_11300110}{out/413\_r\_131\_11300110}}{}{}{out/414_r_131_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.2 alpha 0.7}{\summaryRuleSpan{out/416_r_132_11300110}{out/416\_r\_132\_11300110}}{}{}{out/417_r_132_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.2 inductive 2.7}{\summaryRuleSpan{out/419_r_133_11300110}{out/419\_r\_133\_11300110}}{}{}{out/420_r_133_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.2 alpha 0.6}{\summaryRuleSpan{out/422_r_134_11300110}{out/422\_r\_134\_11300110}}{}{}{out/423_r_134_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.2 rH 2.0}{\summaryRuleSpan{out/425_r_135_11300110}{out/425\_r\_135\_11300110}}{}{}{out/426_r_135_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.2 inductive 1.6}{\summaryRuleSpan{out/428_r_136_11300110}{out/428\_r\_136\_11300110}}{}{}{out/429_r_136_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.2 alpha 3.8}{\summaryRuleSpan{out/431_r_137_11300110}{out/431\_r\_137\_11300110}}{}{}{out/432_r_137_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.3 ind}{\summaryRuleSpan{out/434_r_138_11300110}{out/434\_r\_138\_11300110}}{}{}{out/435_r_138_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.3 alpha}{\summaryRuleSpan{out/437_r_139_11300110}{out/437\_r\_139\_11300110}}{}{}{out/438_r_139_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.4 ind}{\summaryRuleSpan{out/440_r_140_11300110}{out/440\_r\_140\_11300110}}{}{}{out/441_r_140_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.5 row 1}{\summaryRuleSpan{out/443_r_141_11300110}{out/443\_r\_141\_11300110}}{}{}{out/444_r_141_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{monomolecular ion-cleavage 8.5 row 2}{\summaryRuleSpan{out/446_r_142_11300110}{out/446\_r\_142\_11300110}}{}{}{out/447_r_142_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{stepwise symetric openchained intermediate product 8.6 var 1}{\summaryRuleSpan{out/449_r_143_11300110}{out/449\_r\_143\_11300110}}{}{}{out/450_r_143_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{stepwise symetric openchained intermediate product 8.6 var 2}{\summaryRuleSpan{out/452_r_144_11300110}{out/452\_r\_144\_11300110}}{}{}{out/453_r_144_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{stepwise symetric openchained intermediate product 8.6 var 1 alpha}{\summaryRuleSpan{out/455_r_145_11300110}{out/455\_r\_145\_11300110}}{}{}{out/456_r_145_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{stepwise symetric openchained intermediate product 8.6 var 2 alpha}{\summaryRuleSpan{out/458_r_146_11300110}{out/458\_r\_146\_11300110}}{}{}{out/459_r_146_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Hydrogen exchange occring in a Ion-Molecule-Complex 8.7 row 1 rH}{\summaryRuleSpan{out/461_r_147_11300110}{out/461\_r\_147\_11300110}}{}{}{out/462_r_147_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Hydrogen exchange occring in a Ion-Molecule-Complex 8.7 row 1 high energy}{\summaryRuleSpan{out/464_r_148_11300110}{out/464\_r\_148\_11300110}}{}{}{out/465_r_148_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Hydrogen exchange occring in a Ion-Molecule-Complex 8.7 row 2 low energy}{\summaryRuleSpan{out/467_r_149_11300110}{out/467\_r\_149\_11300110}}{}{}{out/468_r_149_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Hydrogen exchange occring in a Ion-Molecule-Complex 8.7 row 3 process 1}{\summaryRuleSpan{out/470_r_150_11300110}{out/470\_r\_150\_11300110}}{}{}{out/471_r_150_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Hydrogen exchange occring in a Ion-Molecule-Complex 8.7 row 3 process 2}{\summaryRuleSpan{out/473_r_151_11300110}{out/473\_r\_151\_11300110}}{}{}{out/474_r_151_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{rearangement with stable Acylium-Ion 8.8 row 1 process 1}{\summaryRuleSpan{out/476_r_152_11300110}{out/476\_r\_152\_11300110}}{}{}{out/477_r_152_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{rearangement with stable Acylium-Ion 8.8 row 1 process 2}{\summaryRuleSpan{out/479_r_153_11300110}{out/479\_r\_153\_11300110}}{}{}{out/480_r_153_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{rearangement with stable Acylium-Ion 8.8 row 1 process 2 back}{\summaryRuleSpan{out/482_r_154_11300110}{out/482\_r\_154\_11300110}}{}{}{out/483_r_154_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{rearangement with stable Acylium-Ion 8.8 row 2 process 2}{\summaryRuleSpan{out/485_r_155_11300110}{out/485\_r\_155\_11300110}}{}{}{out/486_r_155_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{stabil Dienol Ion 8.9 row 1 process 1 rH CH3 §R1}{\summaryRuleSpan{out/488_r_156_11300110}{out/488\_r\_156\_11300110}}{}{}{out/489_r_156_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{stabil Dienol Ion 8.9 row 1 process 2 alpha CH3 §R1}{\summaryRuleSpan{out/491_r_157_11300110}{out/491\_r\_157\_11300110}}{}{}{out/492_r_157_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{stabil Dienol Ion 8.9 row 1 process 1 rH OCH3 §R1}{\summaryRuleSpan{out/494_r_158_11300110}{out/494\_r\_158\_11300110}}{}{}{out/495_r_158_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{stabil Dienol Ion 8.9 row 1 process 2 alpha OCH3 §R1}{\summaryRuleSpan{out/497_r_159_11300110}{out/497\_r\_159\_11300110}}{}{}{out/498_r_159_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Field Rule 8.10 inductive}{\summaryRuleSpan{out/500_r_160_11300110}{out/500\_r\_160\_11300110}}{}{}{out/501_r_160_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Field Rule 8.11 rH}{\summaryRuleSpan{out/503_r_161_11300110}{out/503\_r\_161\_11300110}}{}{}{out/504_r_161_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Field Rule 8.12 ind}{\summaryRuleSpan{out/506_r_162_11300110}{out/506\_r\_162\_11300110}}{}{}{out/507_r_162_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Field Rule 8.13 rH}{\summaryRuleSpan{out/509_r_163_11300110}{out/509\_r\_163\_11300110}}{}{}{out/510_r_163_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Field Rule 8.14 r1p1 rH}{\summaryRuleSpan{out/512_r_164_11300110}{out/512\_r\_164\_11300110}}{}{}{out/513_r_164_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Field Rule 8.14 r1p1 back rH}{\summaryRuleSpan{out/515_r_165_11300110}{out/515\_r\_165\_11300110}}{}{}{out/516_r_165_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Field Rule 8.14 r1p2 rH}{\summaryRuleSpan{out/518_r_166_11300110}{out/518\_r\_166\_11300110}}{}{}{out/519_r_166_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{alpha}{\summaryRuleSpan{out/521_r_167_11300110}{out/521\_r\_167\_11300110}}{}{}{out/522_r_167_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{inductive cleavage f. wiki}{\summaryRuleSpan{out/524_r_168_11300110}{out/524\_r\_168\_11300110}}{}{}{out/525_r_168_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Diels Adler 2 homolysis}{\summaryRuleSpan{out/527_r_170_11300110}{out/527\_r\_170\_11300110}}{}{}{out/528_r_170_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{Diels Adler 3 hetrolysis}{\summaryRuleSpan{out/530_r_171_11300110}{out/530\_r\_171\_11300110}}{}{}{out/531_r_171_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{H rebind Rule}{\summaryRuleSpan{out/533_r_173_11300110}{out/533\_r\_173\_11300110}}{}{}{out/534_r_173_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{rearrangement Rule 1}{\summaryRuleSpan{out/536_r_174_11300110}{out/536\_r\_174\_11300110}}{}{}{out/537_r_174_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{rearrangement Rule 2}{\summaryRuleSpan{out/539_r_175_11300110}{out/539\_r\_175\_11300110}}{}{}{out/540_r_175_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{rearrangment Rule 3}{\summaryRuleSpan{out/542_r_176_11300110}{out/542\_r\_176\_11300110}}{}{}{out/543_r_176_constraints.tex}' >> summary/all.tex
	echo ''
	echo 'Summary compilation disabled by user. Run'
	echo '   mod_post --mode compileSummary'
	echo 'to manually invoke it.'
summary.pdf: summary/all.tex
	mod_post --mode compileSummary
include summary/MakefileImpl
include summary/MakefileDep
include summary/MakefileAllTarget
include summary/MakefileClean
