"""Phase-1 forward-discrimination scorer — the expensive half of the gate.

Where :mod:`discriminate` scores each candidate by its *measured* spectrum (the
oracle library-match bar), this scores each candidate structure by its **MØD
forward prediction**:

    score(candidate) = cosine(observed_true, MØD_predicted(candidate))

The predicted "spectrum" is the set of nominal (rounded) charged-fragment masses
the forward DG produces, weighted by fragment occurrence (an *oracle-Generate +
trivial-Score* arm — no learned intensities yet), preprocessed with the frozen
contract so the cosine is comparable to the observed spectrum. For each target
the true molecule is ranked against its same-formula decoys; the gate question is
whether the true structure ranks first, and how the forward bar compares to the
oracle best-decoy cosine from :mod:`discriminate`.

Coverage-aware: the decoy forward dumps are generated by a SLURM batch that may
still be running, so a candidate is only scored if its dump is **complete** (has a
``.done`` marker) and loadable. Each target reports how many of its decoys were
available, and ranking metrics are computed over the scored candidates only.

Needs ``mod`` (loads DGs) + ``pyarrow``/``rdkit`` (store + formula grouping), so it
runs inside ``mol-spectro.sif`` via ``run/analysis/score_forward.sh``.

Outputs (under ``--out-dir``, default ``data/outputs/metrics``):
  * ``forward_discrimination_per_target.csv``
  * ``forward_discrimination_summary.json``
"""
from __future__ import annotations

import argparse
import csv
import json
import statistics
import traceback
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from src.data_generation import utils
from src.data_generation.analysis.discrimination import build_decoy_set as bds
from src.data_generation.analysis.discrimination import spectrum_ops as so
from src.project_paths import shared_path


def predicted_vector(stems: List[str], fwd_dir: Path, *, weighted: bool) -> Optional[List[float]]:
    """Bin a forward dump's charged-fragment mass-set into a spectrum vector.

    ``stems`` is an ordered list of candidate dump names to try (CAS first, then any
    legacy name), so this works both before and after the CAS rename migration. The
    first complete, loadable dump wins. Masses are rounded to nominal m/z *before*
    binning (so Cl/Br/S fragments land in the right integer bin, matching the ceiling
    metric), then aggregated, sqrt-transformed and L2-normalised like an observed
    spectrum. Returns ``None`` if no candidate dump yields charged fragments.
    """
    for stem in stems:
        if not stem or not utils.dump_is_complete(stem, path=fwd_dir):
            continue
        try:
            # Read the species out of the .pkl rather than loading the DG. Loading registers
            # every species in mod's process-global graph database, so cost grows with
            # everything loaded so far: scoring the full decoy set that way reached 14 GB RSS
            # and decayed from 17 targets/hour to 22 targets/day. Verified to return identical
            # masses AND occurrences on benzene/toluene/catechol/butyric acid/anthracene, at
            # 100-300x the speed. The DG is only needed for per-peak rule provenance, which
            # this function discards anyway.
            spectra = utils.get_spectra_from_dump(stem, path=fwd_dir)
        except Exception:  # noqa: BLE001 - a truncated/odd dump must not kill the run
            continue
        if not spectra:
            continue
        peaks = [(float(round(mass)), float(occ) if weighted else 1.0)
                 for mass, occ, _rules in spectra]
        return so.bin_spectrum(peaks)
    return None


def _rank_of_true(true_score: float, decoy_scores: List[float]) -> Tuple[int, int]:
    """1-based rank of the true score among itself + decoys (ties count against
    the true, i.e. a decoy that equals it ranks above). Returns (rank, n_ties)."""
    better = sum(1 for s in decoy_scores if s > true_score + 1e-12)
    ties = sum(1 for s in decoy_scores if abs(s - true_score) <= 1e-12)
    return better + 1, ties


def score_target(
    name: str,
    smiles: str,
    fwd_dir: Path,
    parquet_dir: Path,
    form2structs: Dict[str, List[dict]],
    key2stems: Dict[str, List[str]],
    *,
    weighted: bool,
    oracle: Dict[str, dict],
) -> Dict[str, object]:
    from rdkit import Chem
    from rdkit.Chem import rdMolDescriptors

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError("unparseable SMILES")
    ikey = Chem.MolToInchiKey(mol)
    formula = rdMolDescriptors.CalcMolFormula(mol)

    record = utils.get_record_by_smiles(smiles, parquet_dir)
    if not record or not record.get("peaks"):
        raise FileNotFoundError("no observed spectrum in store")
    observed = so.bin_spectrum(record["peaks"])

    decoys = [s for s in form2structs.get(formula, []) if s["inchikey"] != ikey]

    row: Dict[str, object] = {
        "name": name, "formula": formula, "cas": record.get("cas", ""),
        "n_decoys_total": len(decoys),
    }

    # CAS-named dump first, human name as a legacy fallback (pre-migration dumps).
    true_stems = [s for s in [str(record.get("cas") or ""), name] if s]
    pred_true = predicted_vector(true_stems, fwd_dir, weighted=weighted)
    row["true_dump"] = bool(pred_true is not None)
    row["forward_true_cosine"] = so.cosine(observed, pred_true) if pred_true is not None else ""

    scored: List[Tuple[float, str]] = []
    for d in decoys:
        vec = predicted_vector(key2stems.get(d["inchikey"], []), fwd_dir, weighted=weighted)
        if vec is None:
            continue
        scored.append((so.cosine(observed, vec), d["name"]))
    scored.sort(key=lambda t: t[0], reverse=True)

    row["n_decoys_scored"] = len(scored)
    # Attach the oracle library-match bar (measured decoy spectra) for comparison.
    orc = oracle.get(name, {})
    row["oracle_best_decoy_cosine"] = orc.get("best_decoy_cosine", "")

    if scored:
        best_cos, best_name = scored[0]
        row["best_forward_decoy_cosine"] = best_cos
        row["best_forward_decoy_name"] = best_name
    else:
        row["best_forward_decoy_cosine"] = ""
        row["best_forward_decoy_name"] = ""

    # Ranking metrics require the true prediction and at least one scored decoy.
    if pred_true is not None and scored:
        true_cos = so.cosine(observed, pred_true)
        rank, ties = _rank_of_true(true_cos, [s for s, _ in scored])
        row["true_rank_forward"] = rank
        row["reciprocal_rank"] = 1.0 / rank
        row["identified_forward"] = bool(rank == 1)
        row["full_coverage"] = bool(len(scored) == len(decoys))
        row["status"] = "ok"
    else:
        row["true_rank_forward"] = ""
        row["reciprocal_rank"] = ""
        row["identified_forward"] = ""
        row["full_coverage"] = ""
        row["status"] = ("no_true_dump" if pred_true is None else "no_decoy_dumps")
    return row


def load_oracle(out_dir: Path) -> Dict[str, dict]:
    """Best-decoy cosine per target from the library-match baseline, if present."""
    path = out_dir / "discrimination_per_target.csv"
    if not path.exists():
        return {}
    oracle: Dict[str, dict] = {}
    with open(path, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if r.get("status") != "ok":
                continue
            try:
                oracle[r["name"]] = {"best_decoy_cosine": float(r["best_decoy_cosine"])}
            except (KeyError, ValueError):
                pass
    return oracle


def summarize(rows: List[Dict[str, object]], config: Dict[str, object]) -> Dict[str, object]:
    ok = [r for r in rows if r.get("status") == "ok"]
    full = [r for r in ok if r.get("full_coverage") is True]

    def _mean(key, src):
        vals = [float(r[key]) for r in src if r.get(key) not in ("", None)]
        return statistics.fmean(vals) if vals else float("nan")

    def _acc(src):
        vals = [r for r in src if isinstance(r.get("identified_forward"), bool)]
        return (sum(1 for r in vals if r["identified_forward"]) / len(vals)) if vals else float("nan")

    # Head-to-head vs the oracle bar, on targets scored with full coverage.
    beats = 0
    comparable = 0
    for r in full:
        o = r.get("oracle_best_decoy_cosine")
        b = r.get("best_forward_decoy_cosine")
        t = r.get("forward_true_cosine")
        if o in ("", None) or b in ("", None) or t in ("", None):
            continue
        comparable += 1
        # Forward "wins" a decoy the same way the oracle does: true prediction
        # must beat the best decoy prediction (already encoded in identified_forward).
        if r.get("identified_forward"):
            beats += 1

    return {
        "config": config,
        "n_targets": len(rows),
        "n_true_dump": sum(1 for r in rows if r.get("true_dump")),
        "n_scored_any": len(ok),
        "n_full_coverage": len(full),
        "forward_top1_accuracy_any_coverage": _acc(ok),
        "forward_top1_accuracy_full_coverage": _acc(full),
        "forward_mrr_any_coverage": _mean("reciprocal_rank", ok),
        "forward_true_cosine_mean": _mean("forward_true_cosine", rows),
        "best_forward_decoy_cosine_mean": _mean("best_forward_decoy_cosine", ok),
        "oracle_best_decoy_cosine_mean_over_scored": _mean("oracle_best_decoy_cosine", ok),
        "n_full_coverage_comparable_to_oracle": comparable,
        "n_full_coverage_identified": beats,
        "hardest_scored": [
            {"name": r["name"], "formula": r["formula"],
             "forward_true_cosine": r.get("forward_true_cosine"),
             "best_forward_decoy_cosine": r.get("best_forward_decoy_cosine"),
             "best_forward_decoy_name": r.get("best_forward_decoy_name"),
             "true_rank_forward": r.get("true_rank_forward")}
            for r in sorted(ok, key=lambda r: (r.get("reciprocal_rank") or 0))[:15]
        ],
    }


def write_csv(rows: List[Dict[str, object]], path: Path) -> None:
    fields: List[str] = []
    for r in rows:
        for k in r:
            if k not in fields:
                fields.append(k)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)


def main() -> None:
    ap = argparse.ArgumentParser(description="Phase-1 forward-discrimination scorer")
    ap.add_argument("--fwd-dir", default=str(shared_path("FWD_DIR_REL")))
    ap.add_argument("--spectra-folder", default=str(shared_path("PARQUET_DIR_REL")))
    ap.add_argument("--compounds-csv", default=str(shared_path("CSV_PATH_REL")))
    ap.add_argument("--out-dir", default=str(shared_path("METRICS_DIR_REL")))
    ap.add_argument("--names", default="", help="Comma-separated subset of target names")
    ap.add_argument("--intensity", choices=["occurrence", "binary"], default="occurrence",
                    help="Predicted-peak weight: fragment occurrence count or 1.0")
    args = ap.parse_args()

    from rdkit import Chem

    fwd_dir = Path(args.fwd_dir)
    parquet_dir = Path(args.spectra_folder)
    out_dir = Path(args.out_dir)
    weighted = args.intensity == "occurrence"

    with open(args.compounds_csv, newline="", encoding="utf-8") as f:
        name2smiles = {str(r["name"]).strip(): str(r["smiles"]).strip()
                       for r in csv.DictReader(f)}
    only = {n.strip() for n in args.names.split(",") if n.strip()} if args.names else None

    # Same RDKit-keyed, isotopologue-filtered structure grouping the decoy batch used.
    form2structs = bds.load_structures_with_spectra(parquet_dir)

    # Dump-stem resolution per structure: CAS first (post-migration), then the legacy
    # names (target human name, or decoy_<inchikey>) so it works mid-transition too.
    target_key2name: Dict[str, str] = {}
    for nm, smi in name2smiles.items():
        m = Chem.MolFromSmiles(smi)
        if m:
            target_key2name[Chem.MolToInchiKey(m)] = nm
    key2stems: Dict[str, List[str]] = {}
    for ss in form2structs.values():
        for s in ss:
            k = s["inchikey"]
            # EVERY registry alias, not just the first store row: a dump is named by the
            # CAS `get_cas_by_smiles` returns, and for same-structure collisions that is
            # often a sibling row. Taking stems[0] alone hid 32 decoys that were on disk.
            stems = list(s.get("cas_all") or [s["cas"]])
            if k in target_key2name:
                stems.append(target_key2name[k])
            stems.append(f"decoy_{k}")
            key2stems[k] = stems

    oracle = load_oracle(out_dir)

    rows: List[Dict[str, object]] = []
    names = sorted(n for n in name2smiles if not only or n in only)
    for i, name in enumerate(names, 1):
        try:
            row = score_target(name, name2smiles[name], fwd_dir, parquet_dir,
                               form2structs, key2stems,
                               weighted=weighted, oracle=oracle)
        except Exception as exc:  # noqa: BLE001
            row = {"name": name, "status": f"error: {exc}"}
            traceback.print_exc()
        rows.append(row)
        if row.get("status") == "ok":
            print(f"  [{i}/{len(names)}] {name}: rank {row['true_rank_forward']} "
                  f"true_cos={float(row['forward_true_cosine']):.3f} "
                  f"best_decoy={float(row['best_forward_decoy_cosine']):.3f} "
                  f"({row['n_decoys_scored']}/{row['n_decoys_total']} decoys)")
        else:
            print(f"  [{i}/{len(names)}] {name}: {row.get('status')}")

    config = {"intensity": args.intensity,
              "binning": "nominal (round) predicted mass; sqrt-intensity, L2, cosine",
              "ion_mode": "EI M+•"}
    summary = summarize(rows, config)

    out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(rows, out_dir / "forward_discrimination_per_target.csv")
    with open(out_dir / "forward_discrimination_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print(f"\nScored {summary['n_scored_any']} targets "
          f"({summary['n_full_coverage']} with full decoy coverage).")
    print(f"Forward top-1: {summary['forward_top1_accuracy_full_coverage']:.3f} (full cov) / "
          f"{summary['forward_top1_accuracy_any_coverage']:.3f} (any cov); "
          f"MRR {summary['forward_mrr_any_coverage']:.3f}")
    print(f"Forward true-cosine mean {summary['forward_true_cosine_mean']:.3f}; "
          f"best forward-decoy {summary['best_forward_decoy_cosine_mean']:.3f} "
          f"vs oracle {summary['oracle_best_decoy_cosine_mean_over_scored']:.3f}")
    print(f"Wrote {out_dir/'forward_discrimination_per_target.csv'} and summary.json")


if __name__ == "__main__":
    main()
